name: Build fonts

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    container:
      image: archlinux/base
    steps:
    - name: Install dependencies
      run: |
        pacman -Sy --noconfirm base git tar python python-pipenv
    - name: Install fontforge
      run: pacman -S --noconfirm fontforge
    - uses: actions/checkout@v2
    - name: Build fonts
      run: |
        pipenv install; pipenv run python build.py
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        token: ${{ secrets.GITHUB_TOKEN }}
